DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS participation_requests CASCADE;
DROP TABLE IF EXISTS event_compilations CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(256)                         NOT NULL,
    name VARCHAR(256)                          NOT NULL,
    CONSTRAINT pk_users                PRIMARY KEY (id),
    CONSTRAINT uq_user_email              UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                           NOT NULL,
    CONSTRAINT pk_categories           PRIMARY KEY (id),
    CONSTRAINT uq_category_name            UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat DOUBLE PRECISION                       NOT NULL,
    lon DOUBLE PRECISION                       NOT NULL,
    radius DOUBLE PRECISION                            ,
    name VARCHAR(256)                                  ,
    address VARCHAR(512)                               ,
    type VARCHAR(256)                                  ,
    CONSTRAINT pk_locations             PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY                                 NOT NULL,
    annotation VARCHAR(2000)                                                   NOT NULL,
    category_id BIGINT                                                         NOT NULL,
    confirmed_requests BIGINT                                        NOT NULL DEFAULT 0,
    created_on TIMESTAMP                                                       NOT NULL,
    description VARCHAR(7000)                                                  NOT NULL,
    event_date TIMESTAMP                                                       NOT NULL,
    initiator_id BIGINT                                                        NOT NULL,
    location_id BIGINT                                                         NOT NULL,
    paid BOOLEAN                                                           DEFAULT TRUE,
    participant_limit INT                                            NOT NULL DEFAULT 0,
    published_on TIMESTAMP                                                             ,
    request_moderation BOOLEAN                                             DEFAULT TRUE,
    state VARCHAR(32)                                                          NOT NULL,
    title VARCHAR(120)                                                         NOT NULL,
    views BIGINT                                                                       ,
    CONSTRAINT pk_events                                               PRIMARY KEY (id),
    CONSTRAINT fk_event_category_id FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT fk_event_user_id FOREIGN KEY (initiator_id)         REFERENCES users(id),
    CONSTRAINT fk_event_location_id FOREIGN KEY (location_id)   REFERENCES locations(id)
);

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY                                          NOT NULL,
    created TIMESTAMP                                                                   NOT NULL,
    event_id BIGINT                                                                     NOT NULL,
    requester_id BIGINT                                                                 NOT NULL,
    status VARCHAR(32)                                                                  NOT NULL,
    CONSTRAINT pk_participation_requests                                        PRIMARY KEY (id),
    CONSTRAINT fk_participation_requests_user_id FOREIGN KEY (requester_id) REFERENCES users(id),
    CONSTRAINT fk_participation_requests_event_id FOREIGN KEY (event_id)    REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                        DEFAULT FALSE,
    title VARCHAR(64)                          NOT NULL,
    CONSTRAINT pk_compilations          PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event_compilations (
    compilation_id                                          BIGINT,
    event_id                                                BIGINT,
    CONSTRAINT pk_comp_event PRIMARY KEY (compilation_id, event_id)
);